# Generated by Django 6.0.4 on 2026-04-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_claim_agent_status_policy_category_user_kyc_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='premium',
        ),
        migrations.AddField(
            model_name='policy',
            name='base_premium',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='policy',
            name='coverage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userpolicy',
            name='premium',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userpolicy',
            name='status',
            field=models.CharField(default='Active', max_length=20),
        ),
    ]
