# Generated by Django 6.0.4 on 2026-04-12 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_claim_amount_claim_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhaar_file', models.FileField(upload_to='kyc/aadhaar/')),
                ('pan_file', models.FileField(upload_to='kyc/pan/')),
                ('selfie_file', models.ImageField(upload_to='kyc/selfie/')),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
