# Generated by Django 6.0.4 on 2026-04-14 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_payment_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='razorpay_payment_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='razorpay_signature',
        ),
        migrations.AddField(
            model_name='claim',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claim_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='claim',
            name='agent_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Assigned', 'Agent Assigned'), ('Verified', 'Agent Verified'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Assigned', 'Agent Assigned'), ('Verified', 'Agent Verified'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(default='success', max_length=20),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_date', models.DateTimeField()),
                ('category', models.CharField(choices=[('health', 'Health Insurance'), ('life', 'Life Insurance'), ('vehicle', 'Vehicle Insurance')], default='health', max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending Assignment'), ('Assigned', 'Agent Assigned'), ('Surveyed', 'Survey Completed'), ('Verified', 'Verified by Admin'), ('Completed', 'Policy Created')], default='Pending', max_length=15)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_tasks', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RenewalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending Assignment'), ('Assigned', 'Agent Assigned'), ('Verified', 'Agent Verified'), ('Approved', 'Approved by Admin'), ('Rejected', 'Rejected')], default='Pending', max_length=15)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('admin_comment', models.TextField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewal_tasks', to=settings.AUTH_USER_MODEL)),
                ('user_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewals', to='accounts.userpolicy')),
            ],
        ),
    ]
