# Generated by Django 6.0.4 on 2026-04-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_payment_bank_name_payment_card_number_masked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='claim_type',
            field=models.CharField(choices=[('Accident', 'Accident / Collision'), ('Medical', 'Medical / Surgery'), ('Theft', 'Theft / Burglary'), ('Damage', 'Property Damage'), ('Other', 'Other Service Request')], default='Accident', max_length=50),
        ),
    ]
