# Generated by Django 6.0.4 on 2026-04-17 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_payment_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
